import Mathlib

-- Valid entities generated by Goedel-Formalizer

-- Entity: obj-term (Regex Fallback)
axiom obj_term : Type

-- Entity: obj-predicate (Regex Fallback)
axiom obj_predicate : Type

-- Entity: obj-wff-fol (Regex Fallback)
axiom obj_wff_fol : Type

