import Mathlib

-- Valid entities generated by Goedel-Formalizer

-- Entity: def-function
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

def Function.IsTotalAndUnique {X Y : Type*} (f : X → Y) : Prop :=
  ∀ x : X, ∃! y : Y, f x = y

-- Entity: def-sequence-uniform-convergence
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

def def_sequence_uniform_convergence (A : Type*) (f : ℕ → A → ℝ) (g : A → ℝ) : Prop :=
  ∀ ε > 0, ∃ N : ℕ, ∀ n > N, ∀ x : A, |f n x - g x| < ε

-- Entity: prop-weierstrass-extreme-value
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

def IsWeierstrassExtremeValue (f : ℝ → ℝ) (a b : ℝ) (ha : a ≤ b) (hf : ContinuousOn f (Set.Icc a b)) : Prop :=
  ∃ x ∈ Set.Icc a b, ∀ y ∈ Set.Icc a b, f y ≤ f x

theorem WeierstrassExtremeValue (f : ℝ → ℝ) (a b : ℝ) (ha : a ≤ b) (hf : ContinuousOn f (Set.Icc a b)) : 
  IsWeierstrassExtremeValue f a b ha hf := by sorry

-- Entity: prop-weierstrass-extreme-value
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

def IsWeierstrassExtremeValue (f : ℝ → ℝ) (a b : ℝ) (ha : a ≤ b) (hf : ContinuousOn f (Set.Icc a b)) : Prop :=
  ∃ x ∈ Set.Icc a b, ∀ y ∈ Set.Icc a b, f y ≤ f x

theorem WeierstrassExtremeValue (f : ℝ → ℝ) (a b : ℝ) (ha : a ≤ b) (hf : ContinuousOn f (Set.Icc a b)) : 
  IsWeierstrassExtremeValue f a b ha hf := by sorry

-- Entity: prop-weierstrass-extreme-value
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

def IsWeierstrassExtremeValue (f : ℝ → ℝ) (a b : ℝ) (ha : a ≤ b) (hf : ContinuousOn f (Set.Icc a b)) : Prop :=
  ∃ x ∈ Set.Icc a b, ∀ y ∈ Set.Icc a b, f y ≤ f x

theorem WeierstrassExtremeValue (f : ℝ → ℝ) (a b : ℝ) (ha : a ≤ b) (hf : ContinuousOn f (Set.Icc a b)) : 
  IsWeierstrassExtremeValue f a b ha hf := by sorry

-- Entity: prop-weierstrass-extreme-value
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

def IsWeierstrassExtremeValue (f : ℝ → ℝ) (a b : ℝ) (ha : a ≤ b) (hf : ContinuousOn f (Set.Icc a b)) : Prop :=
  ∃ x ∈ Set.Icc a b, ∀ y ∈ Set.Icc a b, f y ≤ f x

theorem WeierstrassExtremeValue (f : ℝ → ℝ) (a b : ℝ) (ha : a ≤ b) (hf : ContinuousOn f (Set.Icc a b)) : 
  IsWeierstrassExtremeValue f a b ha hf := by sorry

-- Entity: prop-cantor-uniform-continuity | Type: prop
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

theorem cantor_uniform_continuity (a b : ℝ) (hab : a ≤ b) (f : ℝ → ℝ) 
  (hf : ContinuousOn f (Set.Icc a b)) :
  ∀ ε > 0, ∃ (P : Finset (Set ℝ)), 
    (∀ I ∈ P, ∃ c d : ℝ, c ≤ d ∧ I = Set.Icc c d) ∧
    (⋃ I ∈ P, I) = Set.Icc a b ∧
    (∀ I ∈ P, ∀ x y, x ∈ I → y ∈ I → |f x - f y| < ε) := by sorry

-- Entity: prop-cantor-uniform-continuity
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

theorem cantor_uniform_continuity (a b : ℝ) (hab : a ≤ b) (f : ℝ → ℝ) 
  (hf : ContinuousOn f (Set.Icc a b)) :
  ∀ ε > 0, ∃ (P : Finset (Set ℝ)), 
    (∀ I ∈ P, ∃ c d : ℝ, c ≤ d ∧ I = Set.Icc c d) ∧
    (⋃ I ∈ P, I) = Set.Icc a b ∧
    (∀ I ∈ P, ∀ x y, x ∈ I → y ∈ I → |f x - f y| < ε) := by sorry

-- Entity: prop-cantor-uniform-continuity | Type: prop
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

theorem cantor_uniform_continuity (a b : ℝ) (hab : a ≤ b) :
  ∀ f : ℝ → ℝ, ContinuousOn f (Set.Icc a b) →
  ∀ ε > 0, ∃ P : Set (Set ℝ), 
    (∀ I ∈ P, I ⊆ Set.Icc a b ∧ ∃ x y, I = Set.Icc x y ∧ x ≤ y) ∧
    (∀ I ∈ P, ∀ x y, x ∈ I → y ∈ I → |f x - f y| < ε) := by sorry

-- Entity: prop-cantor-uniform-continuity
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

theorem cantor_uniform_continuity (a b : ℝ) (hab : a ≤ b) :
  ∀ f : ℝ → ℝ, ContinuousOn f (Set.Icc a b) →
  ∀ ε > 0, ∃ P : Set (Set ℝ), 
    (∀ I ∈ P, I ⊆ Set.Icc a b ∧ ∃ x y, I = Set.Icc x y ∧ x ≤ y) ∧
    (∀ I ∈ P, ∀ x y, x ∈ I → y ∈ I → |f x - f y| < ε) := by sorry

-- Entity: prop-cantor-uniform-continuity
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

theorem cantor_uniform_continuity (a b : ℝ) (hab : a ≤ b) :
  ∀ f : ℝ → ℝ, ContinuousOn f (Set.Icc a b) →
  ∀ ε > 0, ∃ P : Set (Set ℝ), 
    (∀ I ∈ P, I ⊆ Set.Icc a b ∧ ∃ x y, I = Set.Icc x y ∧ x ≤ y) ∧
    (∀ I ∈ P, ∀ x y, x ∈ I → y ∈ I → |f x - f y| < ε) := by sorry

-- Entity: prop-cantor-uniform-continuity
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

theorem cantor_uniform_continuity (a b : ℝ) (hab : a ≤ b) :
  ∀ f : ℝ → ℝ, ContinuousOn f (Set.Icc a b) →
  ∀ ε > 0, ∃ P : Set (Set ℝ), 
    (∀ I ∈ P, I ⊆ Set.Icc a b ∧ ∃ x y, I = Set.Icc x y ∧ x ≤ y) ∧
    (∀ I ∈ P, ∀ x y, x ∈ I → y ∈ I → |f x - f y| < ε) := by sorry

-- Entity: prop-cantor-uniform-continuity
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

theorem cantor_uniform_continuity (a b : ℝ) (hab : a ≤ b) :
  ∀ f : ℝ → ℝ, ContinuousOn f (Set.Icc a b) →
  ∀ ε > 0, ∃ P : Set (Set ℝ), 
    (∀ I ∈ P, I ⊆ Set.Icc a b ∧ ∃ x y, I = Set.Icc x y ∧ x ≤ y) ∧
    (∀ I ∈ P, ∀ x y, x ∈ I → y ∈ I → |f x - f y| < ε) := by sorry

-- Entity: prop-cantor-uniform-continuity
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

theorem cantor_uniform_continuity (a b : ℝ) (hab : a ≤ b) :
  ∀ f : ℝ → ℝ, ContinuousOn f (Set.Icc a b) →
  ∀ ε > 0, ∃ P : Set (Set ℝ), 
    (∀ I ∈ P, I ⊆ Set.Icc a b ∧ ∃ x y, I = Set.Icc x y ∧ x ≤ y) ∧
    (∀ I ∈ P, ∀ x y, x ∈ I → y ∈ I → |f x - f y| < ε) := by sorry

-- Entity: prop-cantor-uniform-continuity
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

theorem cantor_uniform_continuity (a b : ℝ) (hab : a ≤ b) :
  ∀ f : ℝ → ℝ, ContinuousOn f (Set.Icc a b) →
  ∀ ε > 0, ∃ P : Set (Set ℝ), 
    (∀ I ∈ P, I ⊆ Set.Icc a b ∧ ∃ x y, I = Set.Icc x y ∧ x ≤ y) ∧
    (∀ I ∈ P, ∀ x y, x ∈ I → y ∈ I → |f x - f y| < ε) := by sorry

-- Entity: prop-cantor-uniform-continuity
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

theorem cantor_uniform_continuity (a b : ℝ) (hab : a ≤ b) :
  ∀ f : ℝ → ℝ, ContinuousOn f (Set.Icc a b) →
  ∀ ε > 0, ∃ P : Set (Set ℝ), 
    (∀ I ∈ P, I ⊆ Set.Icc a b ∧ ∃ x y, I = Set.Icc x y ∧ x ≤ y) ∧
    (∀ I ∈ P, ∀ x y, x ∈ I → y ∈ I → |f x - f y| < ε) := by sorry

-- Entity: prop-cantor-uniform-continuity
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

theorem cantor_uniform_continuity (a b : ℝ) (hab : a ≤ b) :
  ∀ f : ℝ → ℝ, ContinuousOn f (Set.Icc a b) →
  ∀ ε > 0, ∃ P : Set (Set ℝ), 
    (∀ I ∈ P, I ⊆ Set.Icc a b ∧ ∃ x y, I = Set.Icc x y ∧ x ≤ y) ∧
    (∀ I ∈ P, ∀ x y, x ∈ I → y ∈ I → |f x - f y| < ε) := by sorry

-- Entity: prop-cantor-uniform-continuity
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

theorem cantor_uniform_continuity (a b : ℝ) (hab : a ≤ b) :
  ∀ f : ℝ → ℝ, ContinuousOn f (Set.Icc a b) →
  ∀ ε > 0, ∃ P : Set (Set ℝ), 
    (∀ I ∈ P, I ⊆ Set.Icc a b ∧ ∃ x y, I = Set.Icc x y ∧ x ≤ y) ∧
    (∀ I ∈ P, ∀ x y, x ∈ I → y ∈ I → |f x - f y| < ε) := by sorry

-- Entity: prop-cantor-uniform-continuity
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

theorem cantor_uniform_continuity (a b : ℝ) (hab : a ≤ b) :
  ∀ f : ℝ → ℝ, ContinuousOn f (Set.Icc a b) →
  ∀ ε > 0, ∃ P : Set (Set ℝ), 
    (∀ I ∈ P, I ⊆ Set.Icc a b ∧ ∃ x y, I = Set.Icc x y ∧ x ≤ y) ∧
    (∀ I ∈ P, ∀ x y, x ∈ I → y ∈ I → |f x - f y| < ε) := by sorry

-- Entity: prop-cantor-uniform-continuity
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

theorem cantor_uniform_continuity (a b : ℝ) (hab : a ≤ b) :
  ∀ f : ℝ → ℝ, ContinuousOn f (Set.Icc a b) →
  ∀ ε > 0, ∃ P : Set (Set ℝ), 
    (∀ I ∈ P, I ⊆ Set.Icc a b ∧ ∃ x y, I = Set.Icc x y ∧ x ≤ y) ∧
    (∀ I ∈ P, ∀ x y, x ∈ I → y ∈ I → |f x - f y| < ε) := by sorry

-- Entity: prop-cantor-uniform-continuity
import Mathlib
import Aesop

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

theorem cantor_uniform_continuity (a b : ℝ) (hab : a ≤ b) :
  ∀ f : ℝ → ℝ, ContinuousOn f (Set.Icc a b) →
  ∀ ε > 0, ∃ P : Set (Set ℝ), 
    (∀ I ∈ P, I ⊆ Set.Icc a b ∧ ∃ x y, I = Set.Icc x y ∧ x ≤ y) ∧
    (∀ I ∈ P, ∀ x y, x ∈ I → y ∈ I → |f x - f y| < ε) := by sorry

